// header file generated by txt2h, 2003-2006 by ScottManDeath
#ifndef  TXT_HEADER_fragShader
#define  TXT_HEADER_fragShader


std::string  fragShader =
"#version 320 es"
"\n"
"in vec3 fColor; "
"\n"
"out vec4 outColor;"
"\n"
"void main()"
"\n"
"{"
"\n"
"  outColor = vec4(fColor, 1.0); "
"\n"
"}"
"\n"
;


#endif  // #ifdef TXT_HEADER_fragShader
