// header file generated by txt2h, 2003-2006 by ScottManDeath
#ifndef  TXT_HEADER_vert
#define  TXT_HEADER_vert

std::string  vertShader  =
"#version 320 es"
"\n"
"\n"
"in vec2 pos;"
"\n"
"in vec3 color;"
"\n"
"in float sides;"
"\n"
"uniform mat4 MVP;"
"\n"
"\n"
"out vec3 fColor;"
"\n"
"out float vSides;"
"\n"
"\n"
"void main()"
"\n"
"{"
"\n"
"    gl_Position = MVP * vec4(pos, 0.0,0.9);"
"\n"
"    gl_PointSize = 4.0;"
"\n"
"    fColor = color;"
"\n"
"    vSides = sides;"
"\n"
"}"
"\n"
;


#endif  // #ifdef TXT_HEADER_vert
